// generated by scripts/bake-wood.mjs — do not edit
/** the baked wood grain (public/) */
export const WOOD_GRAIN = "/assets/desk/wood-grain.webp"
/** a 48×30 version to paint while WOOD_GRAIN loads */
export const WOOD_GRAIN_LQIP = "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABQAwCdASowAB4APsFeqE+npSOiJWgA8BgJZwDL0oAAK/e8kAD+yL/9fAFPVH1qF22pRWV7jjaMB/dtCG1CfAAA"
